"""added IIT-JEE in topic of question_paper

Revision ID: 11a7ff454687
Revises: ba82280f85f0
Create Date: 2024-01-26 11:39:10.872902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a7ff454687'
down_revision: Union[str, None] = 'ba82280f85f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE question_paper MODIFY COLUMN topic ENUM('PHYSICS', 'MATHS', 'ECONOMICS', 'ACCOUNTING', 'IITJEE') NOT NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE question_paper MODIFY COLUMN topic ENUM('PHYSICS', 'MATHS', 'ECONOMICS', 'ACCOUNTING') NOT NULL;")
    # ### end Alembic commands ###
