"""Add next_steps in user_question_answer

Revision ID: 1a24e25039d7
Revises: 54a3b001eeb4
Create Date: 2024-01-12 13:43:56.664470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a24e25039d7'
down_revision: Union[str, None] = '54a3b001eeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_answer', sa.Column('next_steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_question_answer', 'next_steps')
    # ### end Alembic commands ###
