"""change order of feedback_lenth options

Revision ID: 243641094881
Revises: 5fa00b128ab7
Create Date: 2024-04-02 21:02:59.965051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '243641094881'
down_revision: Union[str, None] = '5fa00b128ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.alter_column('user_question_paper', 'feedback_length',
               existing_type=mysql.ENUM('No', 'Concise', 'Elaborate'),
               type_=sa.Enum('Elaborate', 'Concise', 'No', name='feedbacklength'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_question_paper', 'feedback_length',
               existing_type=sa.Enum('Elaborate', 'Concise', 'No', name='feedbacklength'),
               type_=mysql.ENUM('No', 'Concise', 'Elaborate'),
               existing_nullable=False)
    # ### end Alembic commands ###
