"""add feedback_length_enum to user_question_paper

Revision ID: 265c8ec51a2b
Revises: f5b1a37760dd
Create Date: 2024-01-17 15:30:31.636395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265c8ec51a2b'
down_revision: Union[str, None] = 'f5b1a37760dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_paper', sa.Column('feedback_length', sa.Enum('No', 'Concise', 'Elaborate', name='feedbacklength'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_question_paper', 'feedback_length')
    # ### end Alembic commands ###
