"""add feedback_length to user_question_paper

Revision ID: 37c0c5cd7072
Revises: 6df2add68469
Create Date: 2024-01-17 14:08:20.291545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c0c5cd7072'
down_revision: Union[str, None] = '6df2add68469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_paper', sa.Column('feedback_length', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_question_paper', 'feedback_length')
    # ### end Alembic commands ###
