"""add profile_answer table

Revision ID: 5fa00b128ab7
Revises: 740ee4ecd1ef
Create Date: 2024-04-01 18:19:28.635440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fa00b128ab7'
down_revision: Union[str, None] = '740ee4ecd1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_question_choice_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_question_choice_id'], ['profile_question_choice.id'], ),
    sa.ForeignKeyConstraint(['profile_question_id'], ['profile_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_answer')
    # ### end Alembic commands ###
