"""remove name from table user_role

Revision ID: 8b0e91ef6c7b
Revises: 5e7042396d4b
Create Date: 2024-04-04 15:37:11.634446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b0e91ef6c7b'
down_revision: Union[str, None] = '5e7042396d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_user_role_name', table_name='user_role')
    op.drop_column('user_role', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('ix_user_role_name', 'user_role', ['name'], unique=False)
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
