"""change enum value for understanding_level

Revision ID: a1dd8f54e5ee
Revises: 0406ec759c69
Create Date: 2024-02-01 15:31:50.243628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'a1dd8f54e5ee'
down_revision: Union[str, None] = '0406ec759c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_question_paper', 'understanding_level',
               existing_type=mysql.ENUM('BEGINNER','ADVANCED'),
               type_=sa.Enum('Beginner', 'Advanced', name='understanding_level'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_question_paper', 'understanding_level',
               existing_type=sa.Enum('Beginner', 'Advanced', name='understanding_level'),
               type_=mysql.ENUM('BEGINNER','ADVANCED'),
               existing_nullable=False)
    # ### end Alembic commands ###
