"""change topic to enum in question_paper

Revision ID: a802ee6fe1ba
Revises: ba82280f85f0
Create Date: 2024-01-16 16:57:41.661923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a802ee6fe1ba'
down_revision: Union[str, None] = 'ba82280f85f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_paper', 'topic',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('PHYSICS', 'MATHS', 'ECONOMICS', 'ACCOUNTING', name='topic'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_paper', 'topic',
               existing_type=sa.Enum('PHYSICS', 'MATHS', 'ECONOMICS', 'ACCOUNTING', name='topic'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
