"""Change standard to grade

Revision ID: ba82280f85f0
Revises: fab21c8b4d59
Create Date: 2024-01-14 17:59:36.243923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba82280f85f0'
down_revision: Union[str, None] = 'fab21c8b4d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_paper', sa.Column('grade', sa.Integer(), nullable=True))
    op.drop_column('question_paper', 'standard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_paper', sa.Column('standard', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('question_paper', 'grade')
    # ### end Alembic commands ###
