"""Add enum column

Revision ID: e86f8c7d571f
Revises: 96147d6a5137
Create Date: 2023-12-19 14:32:58.591064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86f8c7d571f'
down_revision: Union[str, None] = '96147d6a5137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('question_paper', sa.Column('state', sa.Enum('COMPLETED', 'DRAFTED', name='state'), nullable=True))

    question_paper = sa.table('question_paper', sa.column('state', sa.Enum('COMPLETED', 'DRAFTED', name='state')))
    op.execute(
        question_paper.update().values(state='COMPLETED')
    )

    op.alter_column('question_paper', 'state', existing_type=sa.Enum('COMPLETED', 'DRAFTED', name='state'), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_paper', 'state')
    # ### end Alembic commands ###
