"""add feedback_length to user_question_paper

Revision ID: f5b1a37760dd
Revises: 37c0c5cd7072
Create Date: 2024-01-17 14:42:27.531114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5b1a37760dd'
down_revision: Union[str, None] = '37c0c5cd7072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_question_paper', 'feedback_length')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_paper', sa.Column('feedback_length', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
