"""Change board to enum

Revision ID: fab21c8b4d59
Revises: c91beac59f03
Create Date: 2024-01-13 12:31:42.855621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fab21c8b4d59'
down_revision: Union[str, None] = 'c91beac59f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_paper', 'board',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('IGCSE', 'ICSE', 'CBSE', 'IB', name='board'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_paper', 'board',
               existing_type=sa.Enum('IGCSE', 'ICSE', 'CBSE', 'IB', name='board'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
